config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
 resources :contacts
 
  resources :users do
    resource :profile
  end
 get '/' => 'pages#home'

 get '/about' => 'pages#about'

 post '/thanks' => 'pages#thanks'

 

 get '/check_email' => 'contacts#check_email',  :defaults => { :format => 'json' }

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    
has_many :users
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
 belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

belongs_to :plan
has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
     
 def new
   @flash1 = Hash.new
#  @flash1[:success] = 'sds'
   @contact = Contact.new
 end
 
 def thanks
 end
 
 #def create
  # @contact = Contact.new(contact_params)
 
   #if @contact.save
  
    # @myarray = {:status => "success"};
     # redirect_to new_contact_path
     
   #else 
    # @myarray = {:status => "failure"};
     #redirect_to new_contact_path
   #end
  
 #end
def create
  @contact = Contact.new(contact_params)
    @flash1 = Hash.new
    if(Contact.find_by_email(@contact.email))
      if(@contact.email == Contact.find_by_email(@contact.email).email)
  redirect_to new_contact_path(:something => "else")
  return
      end

    end

  if @contact.save
    name = params[:contact][:name]
    email = params[:contact][:email]
    body = params[:contact][:comments]
    ContactMailer.contact_email(name, email, body).deliver
    @flash1[:success] = 'Message sent.'
   redirect_to contact_path(:id => @contact.id) 
  else
   @flash1[:success] = 'Error occured, message has not been sent.'
    redirect_to :action => :show
  end
 
end



def show
  @user = Contact.find(params[:id]);
end

def check_email
 puts params[:email]
@userr = Contact.find_by_email(params[:contact][:email])

respond_to do |format|
#format.html { render(:text => !@userr) }
format.json { render :json => !@userr }
end
end



 private  
 def contact_params
  params.require(:contact).permit(:name, :email, :commets)
 end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    
    end
    
    def home1
    end
    
    
    def about
    end
    
    def thanks
end
        
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def new
    
    @user = User.find( params[:user_id] )
    @variable = params[:hello]
    @profile = @user.build_profile
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<html>
  <head>
  

  </head>
  
    <title>
        New Contacts!
    </title>
    <body>
       <h1><%= params[:something]%> </h1>
         
      <div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-success' %>
      <% end %>
    </div>

    
  </div>
</div>

    </body>
</html>

app/views/contacts/show.html.erb
<!-- <h1><%= params[:success] %> </h1> -->

<html>
    <title>
        None
    </title>
    <body>
        <H1> Hellsdso World!</H1>
        <h1><%= @user.email %>
     
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimplecodecastsSaas</title>

<%= stylesheet_link_tag 'application' %>


<%= javascript_include_tag 'application' %>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<%= csrf_meta_tags %>

</head>
<body>
<nav class="navbar navbar-default navbar-static-top" role="navigation">

  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
             
      <a class="navbar-brand" href="/">
       //
        <i class="fa fa-users"></i>
        <i class="fa fa-thumbs-up"></i>
       // <!-- <span class="glyphicon glyphicon-euro" aria-hidden="true"></span> -->
        We <3 Developers :)
      </a>
   
  </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "We <3 Feedback", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>


  <div>
 
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<html>
    <title>
        None
    </title>
    <body>
        <H1> Hello World!</H1>
        
    </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
          <%= link_to "Create your dayum Profile Baby!", new_user_profile_path(current_user), class: 'btn btn-success navbar-btn', method: :get %>
        <% end %>
        
        
        <script src="https://apis.google.com/js/platform.js" async defer></script>
<div class="g-hangout" data-render="createhangout"></div>

<script language="javascript" type="text/javascript">
  
    
    function makeid()
{
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for( var i=0; i < 17; i++ )
        text += possible.charAt(Math.floor(Math.random() * possible.length));

    return text;
}

  var string = makeid(); 
  
  var string2 = "https://plus.google.com/hangouts/_/event/" + string + "?authuser=0&hl=en-GB";
console.log(string2)


document.write('<a href="' + string2 + '">Link text</a>');

document.getElementById("link2").setAttribute("href","sdfsf");
</script>




<div class = "jumbotron">
    <div class = "container-fluid">
        <h1 id"link2">dsfadfs</h1>
        <h1>Welcome</h1>
        <h2>Hi Developers!</h2>
        
    </div>
</div>

app/views/pages/home1.html.erb
<html>
  <head>
    <script type="text/javascript">
      // Your Client ID can be retrieved from your project in the Google
      // Developer Console, https://console.developers.google.com
      var CLIENT_ID = '172356446067-c2capgvo6c5ib8hfhpn5uulkp2vrnja1.apps.googleusercontent.com';

      var SCOPES = ["https://www.googleapis.com/auth/calendar"];

      /**
       * Check if current user has authorized this application.
       */
      function checkAuth() {
        gapi.auth.authorize(
          {
            'client_id': CLIENT_ID,
            'scope': SCOPES,
            'immediate': true
          }, handleAuthResult);
      }

      /**
       * Handle response from authorization server.
       *
       * @param {Object} authResult Authorization result.
       */
      function handleAuthResult(authResult) {
        var authorizeDiv = document.getElementById('authorize-div');
        if (authResult && !authResult.error) {
          // Hide auth UI, then load client library.
          authorizeDiv.style.display = 'none';
          loadCalendarApi();
        } else {
          // Show auth UI, allowing the user to initiate authorization by
          // clicking authorize button.
          authorizeDiv.style.display = 'inline';
        }
      }

      /**
       * Initiate auth flow in response to user clicking authorize button.
       *
       * @param {Event} event Button click event.
       */
      function handleAuthClick(event) {
        gapi.auth.authorize(
          {client_id: CLIENT_ID, scope: SCOPES, immediate: false},
          handleAuthResult);
        return false;
      }

      /**
       * Load Google Calendar client library. List upcoming events
       * once client library is loaded.
       */
      function loadCalendarApi() {
        gapi.client.load('calendar', 'v3', listUpcomingEventss);
      }

      /**
       * Print the summary and start datetime/date of the next ten events in
       * the authorized user's calendar. If no events are found an
       * appropriate message is printed.
       */
       
       function listUpcomingEventss(){
           
           
      var event = {
  'summary': 'Karan Singh',
  'location': '800 Howard St., San Francisco, CA 94103',
  'description': 'A chance to hear more about Google\'s developer products.',
  'start': {
    'dateTime': '2015-11-28T09:00:00-07:00',
    'timeZone': 'America/Los_Angeles'
  },
  'end': {
    'dateTime': '2015-11-28T10:00:00-07:00',
    'timeZone': 'America/Los_Angeles'
  },
  'recurrence': [
    'RRULE:FREQ=DAILY;COUNT=2'
  ],
 
  'reminders': {
    'useDefault': false,
    'overrides': [
      {'method': 'email', 'minutes': 24 * 60},
      {'method': 'popup', 'minutes': 10}
    ]
  }
};

var request = gapi.client.calendar.events.insert({
  'calendarId': 'primary',
  'resource': event
});

request.execute(function(event) {
  appendPre('Event created: ' + event.htmlLink + event.hangoutLink);
});
       }
      function listUpcomingEvents() {
        var request = gapi.client.calendar.events.list({
          'calendarId': 'primary',
          'timeMin': (new Date()).toISOString(),
          'showDeleted': false,
          'singleEvents': true,
          'maxResults': 10,
          'orderBy': 'startTime'
        });

        request.execute(function(resp) {
          var events = resp.items;
          appendPre('Upcoming events:');

          if (events.length > 0) {
            for (i = 0; i < events.length; i++) {
              var event = events[i];
              var when = event.start.dateTime;
              if (!when) {
                when = event.start.date;
              }
              appendPre(event.summary + ' (' + when + ')')
            }
          } else {
            appendPre('No upcoming events found.');
          }

        });
      }

      /**
       * Append a pre element to the body containing the given message
       * as its text node.
       *
       * @param {string} message Text to be placed in pre element.
       */
      function appendPre(message) {
        var pre = document.getElementById('output');
        var textContent = document.createTextNode(message + '\n');
        pre.appendChild(textContent);
        
        
      
      }
      
    </script>
    <script src="https://apis.google.com/js/client.js?onload=checkAuth">
    </script>
  </head>
  <body>
    <div id="authorize-div" style="display: none">
      <span>Authorize access to Google Calendar API</span>
      <!--Button for the user to click to initiate auth sequence -->
      <button id="authorize-button" onclick="handleAuthClick(event)">
        Authorize
      </button>
    </div>
    <pre id="output"></pre>
  </body>
</html>

app/views/pages/thanks.html.erb
<!-- <h1><%= params[:success] %> </h1> -->

<html>
    <title>
        None
    </title>
    <body>
        <H1> Hellsdso World!</H1>
        
    </body>
</html>